#ifndef MICROPY_INCLUDED_ULAB_GET_MAGNETIC_FIELD_SERIES_H
#define MICROPY_INCLUDED_ULAB_GET_MAGNETIC_FIELD_SERIES_H

#include "py/obj.h"
#include "py/objarray.h"


#endif //MICROPY_INCLUDED_ULAB_GET_MAGNETIC_FIELD_SERIES_H